### ISSUE TITLE
It could be useful to document LexoRank.parse in the readme

### ISSUE THREAD

**Issue by maelchiotti** [FLYINGKRIPTO/lexo_rank#1]
I store the indexes generated by your awesome package as text in my database, so when I need to generate a new index I usually don't have a LexoRank object. I had to look at the source code to understand that I could just parse my strings (which is very easy), but I think it would be great to add it to the readme as most people should be in a similar situation.

Anyway thank you for your work it made ranking things in my project so easy!

**Comment by FLYINGKRIPTO** [comment]
Thanks @maelchiotti  for this suggestion, I have added the documentation. As you are using the package feel free to raise issues if any
